### ISSUE TITLE
pip installation doesn't seem to work

### ISSUE THREAD

**Issue by curldivergence** [kecho/coalpy#1]
Hi, thanks once again for this project :) Unfortunately `pip install` didn't work for me:
```
(base) C:\Dev\coalpy>pip install coalpy
Collecting coalpy
  Downloading coalpy-0.0.6-py3-none-any.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 1.7 MB/s
Installing collected packages: coalpy
Successfully installed coalpy-0.0.6

(base) C:\Dev\coalpy>python -m coalpy.examples.seascape
Traceback (most recent call last):
  File "C:\Users\andrew\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\andrew\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\andrew\anaconda3\lib\site-packages\coalpy\examples\seascape.py", line 1, in <module>
    import coalpy.gpu as gpu
ImportError: DLL load failed while importing gpu: The specified module could not be found.
```

My environment is anaconda:
```
(base) C:\Dev\coalpy>conda --version
conda 4.10.1
```

Please let me know if you need any more details.

Thanks!

**Comment by curldivergence** [comment]
UPD: unfortunately manual build and installation from wheel do not work for me either :(
```
(base) C:\Dev\coalpy\t2-output\win64-msvc-debug-default\coalpy_pip\dist>pip install wheel
Requirement already satisfied: wheel in c:\users\andrew\anaconda3\lib\site-packages (0.36.2)

(base) C:\Dev\coalpy\t2-output\win64-msvc-debug-default\coalpy_pip\dist>pip install coalpy-0.0.6-py3-none-any.whl
Processing c:\dev\coalpy\t2-output\win64-msvc-debug-default\coalpy_pip\dist\coalpy-0.0.6-py3-none-any.whl
Installing collected packages: coalpy
Successfully installed coalpy-0.0.6

(base) C:\Dev\coalpy\t2-output\win64-msvc-debug-default\coalpy_pip\dist>python -m coalpy.examples.seascape
Traceback (most recent call last):
  File "C:\Users\andrew\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\andrew\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\andrew\anaconda3\lib\site-packages\coalpy\examples\seascape.py", line 1, in <module>
    import coalpy.gpu as gpu
ImportError: DLL load failed while importing gpu: The specified module could not be found.
```

**Comment by curldivergence** [comment]
Sorry, missed the fact that my Python was pre-3.9 :) It works out of the box after updating.

**Comment by kecho** [comment]
cheers mate! glad it worked!
